version: '3.5'

services:
    www:
        container_name: web
        image: webdevops/php-nginx-dev:8.1
        working_dir: /app
        volumes:
          - ./:/app
          - ./docker_nginx_vhost.conf:/opt/docker/etc/nginx/vhost.conf
        user: 1000:1000
        ports:
          - '${APP_PORT:-80}:80'
        depends_on:
          - redis
          - db

#    npm:
#        container_name: npm
#        image: node:current-alpine
#        working_dir: /app
#        volumes:
#            - ./:/app

    redis:
        container_name: redis
        image: redis

    db:
        container_name: db
        image: mysql:8.0.27
        working_dir: /application
        command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --max_allowed_packet=33554432]
        volumes:
          - restaurant-database:/var/lib/mysql
        environment:
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_USER: ${DB_USERNAME}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

volumes:
    restaurant-database:

